apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customer-pvc-1
  namespace: customer-accounts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

