apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: ebs.csi.aws.com
parameters:
  type: gp2  # General Purpose SSD (update based on your use case)
reclaimPolicy: Delete
volumeBindingMode: Immediate

